### ISSUE TITLE
Parabolic arc

### ISSUE THREAD

**Issue by piller187** [kikito/tween.lua#12]
Is there any way to get this tween library to do a parabolic arc (like throwing a grenade)? I use this library pretty extensively in the Leadwerks engine and would love to be able to use it for a parabolic arc movement.

**Comment by kikito** [comment]
Hi there,

None of the available easing functions will allow you to do that. You have two options: either you provide your own easing function which provides a parabolic arc, or you use two tweens: one to "reach the top of the arc" and another one to "go from the top of the arc to the target". The most appropiate easing function if you are using the two-tweens approach is `outQuad`.

Regards!

**Comment by piller187** [comment]
Oh 2 tweens, I didn't even think about that! That could work for sure! Thanks for the suggestion.
