### ISSUE TITLE
inExpo cannot end on 'c' value

### ISSUE THREAD

**Issue by fnaith** [kikito/tween.lua#17]
I used to insert `if t == d then return b + c end` to solve it for my project, like following:

`local function inExpo(t, b, c, d)
  if t == 0 then return b end
  if t == d then return b + c end
  return c * pow(2, 10 * (t / d - 1)) + b - c * 0.001
end`

But now I am really curious to know why ` - c * 0.001` shown in this function.

It is more like a question about why this implementation does not following [others](http://robertpenner.com/easing/)

**Comment by fnaith** [comment]
After digging issues from [tweener](https://code.google.com/archive/p/tweener/), I found a description in [issue #9](https://code.google.com/archive/p/tweener/issues/9) : 

> Posted on May 28, 2007 by Grumpy Rhino
Ok, I've been testing and I was able to test this. Indeed, there's a certain snap under these conditions:
using the default ("easeoutexpo") transition only, apparently;
moving from a log distance (as mentioned).
Because the equation function tries to approach the result of an exponential progression, there's a slight error before the final frame of the animation; the error margin seems to be exactly 0.1% of the total moved area.
It has been featured on Robert Penner's equations since they've been released, so you can see the same problem with MC Tween or with any other Tweening engine. Funny enough, it's the first time I see this snap being discussed. Odd.

Turns out the `- c * 0.001` presents some numerical analysis knowledge. Case close.

**Comment by kikito** [comment]
Hey, I didn't have time during holidays to look at this. I'm glad you consider this closed then. Happy new year!

**Comment by fnaith** [comment]
Well, I'm glad you brought brilliant implementation to Lua and took testing seriously.

Happy new year !
